controls:
  CheckBoxControl:
    display_name: Checkbox
    category: all
  TextControl:
    display_name: Text
    category: all
  ButtonControl:
    display_name: Button
    category: all
  TextboxControl:
    display_name: Textfield
    category: all
  HeadingControl:
    display_name: Headings
    category: all
  AlertControl:
    display_name: Alert
    category: all
  ButtonGroupControl:
    display_name: Button Group
    category: all
  PaginationControl:
    display_name: Pagination
    category: all
  NavbarControl:
    display_name: Navigation Bar
    category: all
  LinkControl:
    display_name: Link
    category: all
  WellControl:
    display_name: Well
    category: all
  ProgressBarControl:
    display_name: Progress Bar
    category: all
  ProgressBarControl:
    display_name: Progress Bar
    category: all
  BreadcrumbControl:
    display_name: Breadcrumb
  ButtonAddons:
    display_name: Button Addons
  BadgeControl:
    display_name: Badge Control
    category: all
